[book]
title = "Diego Pacheco's Software Architecture Library"
authors = ["Diego Pacheco"]
language = "en"
src = "src"

[output.html]
mathjax-support = true
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/diegopacheco/diegopacheco-architecture-library"
additional-css = ["theme/custom.css"]
additional-js = ["theme/version.js","js/years.js"]
